# 第一阶段：构建环境
FROM alpine:latest AS builder
ARG NGINX_VERSION=1.25.3 ZSTD_VERSION=1.5.5

RUN apk add --no-cache pcre-dev zlib-dev openssl-dev wget git build-base brotli-dev \
    libxml2-dev libxslt-dev curl-dev yajl-dev lmdb-dev geoip-dev lua-dev \
    automake autoconf libtool pkgconfig linux-headers pcre2-dev

WORKDIR /usr/src

# 下载NGINX
RUN wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
    && tar -zxf nginx-${NGINX_VERSION}.tar.gz

# 克隆Brotli模块
RUN git clone --recurse-submodules -j8 https://github.com/google/ngx_brotli

# 克隆和构建ModSecurity
RUN git clone --depth 1 https://github.com/owasp-modsecurity/ModSecurity \
    && cd ModSecurity \
    && git submodule init \
    && git submodule update \
    && ./build.sh \
    && ./configure \
    && make && make install \
    && cd ..

# 克隆ModSecurity NGINX模块
RUN git clone https://github.com/owasp-modsecurity/ModSecurity-nginx

# 下载和构建Zstandard
RUN wget https://github.com/facebook/zstd/releases/download/v${ZSTD_VERSION}/zstd-${ZSTD_VERSION}.tar.gz \
    && tar -xzf zstd-${ZSTD_VERSION}.tar.gz \
    && cd zstd-${ZSTD_VERSION} \
    && make clean \
    && CFLAGS="-fPIC" make && make install \
    && cd ..

# 克隆Zstandard NGINX模块
RUN git clone --depth=10 https://github.com/tokers/zstd-nginx-module.git

# 配置和构建NGINX
RUN cd nginx-${NGINX_VERSION} && \
    ./configure --with-compat \
                --add-dynamic-module=../ngx_brotli \
                --add-dynamic-module=../ModSecurity-nginx \
                --add-dynamic-module=../zstd-nginx-module && \
    make modules

# 第二阶段：运行环境
FROM nginx:alpine
ARG NGINX_VERSION=1.25.3 CORERULESET_VERSION=4.0.0-rc1

# 复制模块和库文件
COPY --from=builder /usr/src/nginx-${NGINX_VERSION}/objs/*.so /etc/nginx/modules/
COPY --from=builder /usr/local/modsecurity/lib/* /usr/lib/

# 创建WAF目录并配置
RUN mkdir -p /etc/nginx/modsec/plugins \
    && wget https://github.com/coreruleset/coreruleset/archive/v${CORERULESET_VERSION}.tar.gz \
    && tar -xzf v${CORERULESET_VERSION}.tar.gz --strip-components=1 -C /etc/nginx/modsec \
    && rm -f v${CORERULESET_VERSION}.tar.gz \
    && wget -P /etc/nginx/modsec/plugins https://raw.githubusercontent.com/coreruleset/wordpress-rule-exclusions-plugin/master/plugins/wordpress-rule-exclusions-before.conf \
    && wget -P /etc/nginx/modsec/plugins https://raw.githubusercontent.com/coreruleset/wordpress-rule-exclusions-plugin/master/plugins/wordpress-rule-exclusions-config.conf \
    && wget -P /etc/nginx/modsec/plugins https://raw.githubusercontent.com/kejilion/nginx/main/waf/ldnmp-before.conf \
    && cp /etc/nginx/modsec/crs-setup.conf.example /etc/nginx/modsec/crs-setup.conf \
    && echo 'SecAction "id:900110, phase:1, pass, setvar:tx.inbound_anomaly_score_threshold=30, setvar:tx.outbound_anomaly_score_threshold=16"' >> /etc/nginx/modsec/crs-setup.conf \
    && wget https://raw.githubusercontent.com/owasp-modsecurity/ModSecurity/v3/master/modsecurity.conf-recommended -O /etc/nginx/modsec/modsecurity.conf \
    && sed -i 's/SecRuleEngine DetectionOnly/SecRuleEngine On/' /etc/nginx/modsec/modsecurity.conf \
    && sed -i 's/SecPcreMatchLimit [0-9]\+/SecPcreMatchLimit 20000/' /etc/nginx/modsec/modsecurity.conf \
    && sed -i 's/SecPcreMatchLimitRecursion [0-9]\+/SecPcreMatchLimitRecursion 20000/' /etc/nginx/modsec/modsecurity.conf \
    && sed -i 's/^SecRequestBodyLimit\s\+[0-9]\+/SecRequestBodyLimit 52428800/' /etc/nginx/modsec/modsecurity.conf \
    && sed -i 's/^SecRequestBodyNoFilesLimit\s\+[0-9]\+/SecRequestBodyNoFilesLimit 524288/' /etc/nginx/modsec/modsecurity.conf \
    && sed -i 's/^SecAuditEngine RelevantOnly/SecAuditEngine Off/' /etc/nginx/modsec/modsecurity.conf \
    && echo 'Include /etc/nginx/modsec/crs-setup.conf' >> /etc/nginx/modsec/modsecurity.conf \
    && echo 'Include /etc/nginx/modsec/plugins/*-config.conf' >> /etc/nginx/modsec/modsecurity.conf \
    && echo 'Include /etc/nginx/modsec/plugins/*-before.conf' >> /etc/nginx/modsec/modsecurity.conf \
    && echo 'Include /etc/nginx/modsec/rules/*.conf' >> /etc/nginx/modsec/modsecurity.conf \
    && echo 'Include /etc/nginx/modsec/plugins/*-after.conf' >> /etc/nginx/modsec/modsecurity.conf \
    && apk add --no-cache lua5.1 lua5.1-dev pcre pcre-dev yajl yajl-dev \
    && ldconfig /usr/lib \
    && wget https://raw.githubusercontent.com/owasp-modsecurity/ModSecurity/v3/master/unicode.mapping -O /etc/nginx/modsec/unicode.mapping \
    && rm -rf /var/cache/apk/*

# 添加质询页面和配置
COPY challenge.html /usr/share/nginx/html/challenge.html
RUN echo 'SecRule TX:ANOMALY_SCORE "@gt 0" "id:1000,phase:4,chain,log,redirect:/challenge.html?url=%{request_uri}&score=%{tx.anomaly_score}"' >> /etc/nginx/modsec/modsecurity.conf \
    && echo 'SecRule REQUEST_HEADERS:Cookie "!@contains waf_validated=true"' >> /etc/nginx/modsec/modsecurity.conf \
    && echo 'SecRule TX:ANOMALY_SCORE "@lt %{tx.inbound_anomaly_score_threshold}" "id:1001,phase:5,nolog,pass"' >> /etc/nginx/modsec/modsecurity.conf \
    && sed -i '1i load_module modules/ngx_http_modsecurity_module.so;' /etc/nginx/nginx.conf \
    && sed -i '/http {/a \    modsecurity on;\n    modsecurity_rules_file /etc/nginx/modsec/modsecurity.conf;' /etc/nginx/nginx.conf
